/**
 * Generates neutral placeholder images in the brand palette plus a
 * `lib/images.ts` manifest with width, height and a blurDataURL for each.
 *
 * Run after swapping real photos into /public/placeholder to refresh blur data:
 *   npm run placeholders -- --manifest-only
 */
import sharp from "sharp";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const dir = path.join(root, "public", "placeholder");
const ogDir = path.join(root, "public", "og");
const manifestOnly = process.argv.includes("--manifest-only");

const CHARCOAL = "#343333";
const POWDER = "#B8C6CC";
const BONE = "#C4C0BC";
const COTTON = "#E8E8E4";

/** name -> [width, height, tone] */
const specs = {
  "hero-clinic-2400x1600.jpg": [2400, 1600, "dark"],
  "why-sterilization-1600x1200.jpg": [1600, 1200, "light"],
  "why-one-trip-1600x1200.jpg": [1600, 1200, "mid"],
  "why-location-1600x1200.jpg": [1600, 1200, "light"],
  "why-schedule-1600x1200.jpg": [1600, 1200, "light"],
  "why-payments-1600x1200.jpg": [1600, 1200, "mid"],
  "why-family-1600x1200.jpg": [1600, 1200, "light"],
  "ba-veneers-before-1200x900.jpg": [1200, 900, "mid"],
  "ba-veneers-after-1200x900.jpg": [1200, 900, "light"],
  "ba-implant-before-1200x900.jpg": [1200, 900, "mid"],
  "ba-implant-after-1200x900.jpg": [1200, 900, "light"],
  "ba-whitening-before-1200x900.jpg": [1200, 900, "mid"],
  "ba-whitening-after-1200x900.jpg": [1200, 900, "light"],
  "doctor-portrait-1200x1500.jpg": [1200, 1500, "dark"],
};

function svgFor(w, h, tone, label) {
  const [a, b] =
    tone === "dark" ? [CHARCOAL, "#4a4f57"] : tone === "mid" ? [POWDER, BONE] : [COTTON, POWDER];
  const text = tone === "dark" ? COTTON : CHARCOAL;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <radialGradient id="g" cx="35%" cy="30%" r="90%">
      <stop offset="0" stop-color="${b}"/>
      <stop offset="1" stop-color="${a}"/>
    </radialGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="url(#g)"/>
  <text x="${w / 2}" y="${h / 2}" fill="${text}" fill-opacity="0.35" font-family="Helvetica, Arial, sans-serif" font-size="${Math.round(w / 36)}" text-anchor="middle" dominant-baseline="middle" letter-spacing="2">${label}</text>
</svg>`;
}

async function generate() {
  await mkdir(dir, { recursive: true });
  await mkdir(ogDir, { recursive: true });
  for (const [name, [w, h, tone]] of Object.entries(specs)) {
    const label = name.replace(/-\d+x\d+\.jpg$/, "").replace(/-/g, " ").toUpperCase();
    await sharp(Buffer.from(svgFor(w, h, tone, label)))
      .jpeg({ quality: 78, mozjpeg: true })
      .toFile(path.join(dir, name));
  }
  for (const lang of ["en", "es"]) {
    await sharp(Buffer.from(svgFor(1200, 630, "dark", `MYDENTIST SAN CARLOS ${lang.toUpperCase()}`)))
      .jpeg({ quality: 82, mozjpeg: true })
      .toFile(path.join(ogDir, `og-${lang}-1200x630.jpg`));
  }
}

async function manifest() {
  const files = (await readdir(dir)).filter((f) => /\.(jpe?g|png|webp|avif)$/i.test(f)).sort();
  const entries = [];
  for (const f of files) {
    const img = sharp(path.join(dir, f));
    const meta = await img.metadata();
    const blur = await img.resize(12).jpeg({ quality: 40 }).toBuffer();
    entries.push(
      `  "/placeholder/${f}": { width: ${meta.width}, height: ${meta.height}, blurDataURL: "data:image/jpeg;base64,${blur.toString("base64")}" },`,
    );
  }
  const out = `/**
 * Generated by scripts/placeholders.mjs. Do not edit by hand.
 * Re-run \`npm run placeholders -- --manifest-only\` after swapping images.
 */
export type ImageMeta = { width: number; height: number; blurDataURL: string };

export const images = {
${entries.join("\n")}
} as const satisfies Record<string, ImageMeta>;

export type ImageSrc = keyof typeof images;

export function imageMeta(src: string): ImageMeta {
  const meta = (images as Record<string, ImageMeta>)[src];
  if (!meta) throw new Error(\`No image metadata for \${src}. Run npm run placeholders -- --manifest-only\`);
  return meta;
}
`;
  await writeFile(path.join(root, "lib", "images.ts"), out);
  console.log(`lib/images.ts written with ${entries.length} images`);
}

if (!manifestOnly) await generate();
await manifest();
